language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
# command to install dependencies
install:
  - pip install tox
# command to run tests
script:
  - tox
before_install:
  - pip install codecov
after_success:
  - codecov
