language: python
python: 3.7
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - coverage run --source m2m setup.py test
before_install:
  - pip install codecov
after_success:
  - codecov
