language: python
matrix:
    include:
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
        - python: 3.8
          env: TOXENV=py38
# command to install dependencies
install:
  - pip install tox
# command to run tests
script:
  - tox
before_install:
  - pip install codecov
after_success:
  - codecov
